### ISSUE TITLE
Replace `mdn-browser-compat-data` to `@mdn/browser-compat-data`

### ISSUE THREAD

**Issue by Semigradsky** [amilajack/ast-metadata-inferer#129]
`mdn-browser-compat-data` is deprecated and no maintained.

**Comment by amilajack** [comment]
Fixed in `@latest`

**Comment by Semigradsky** [comment]
@amilajack `mdn-browser-compat-data` stll used:
https://github.com/amilajack/ast-metadata-inferer/blob/3b0188b192c77caa8cd3984ef21da5c55f80e553/src/providers/mdn/index.ts#L2
