### ISSUE TITLE
ES2021 features are not present in electron 8.5.5

### ISSUE THREAD

**Issue by sam016** [amilajack/ast-metadata-inferer#136]
`ast-metadata-inferer` is missing the ES2021 features like `String.prototype.replaceAll`.

Please refer to the following image for reference:
![image](https://user-images.githubusercontent.com/8340854/128694796-aca28bb2-8ce7-4035-a812-9ec56a8c04b6.png)

**FIX**
Upgrading to electron 10.4.7 or 11.4.11 would fix it.

![image](https://user-images.githubusercontent.com/8340854/128717194-031074f7-942c-433b-a33f-2e4c9354f947.png)

![image](https://user-images.githubusercontent.com/8340854/128717356-a7250064-0cc6-4d8e-8077-99db6e12fe22.png)

**Comment by sam016** [comment]
Heads up, if someone is trying to upgrade electron to v12+.
I spent some time trying to set up `nightmare` with `electron` v12+, but there is some misconfiguration b/w them and it does not work well.

**Comment by amilajack** [comment]
Thanks for calling this out! I've fixed this in https://github.com/amilajack/ast-metadata-inferer/commit/17af22c805a850a726ac342595a4dfa98beebd51. I'll open another issue for migrating from electron 10 to 12
