### ISSUE TITLE
migrate to electron 12

### ISSUE THREAD

**Issue by amilajack** [amilajack/ast-metadata-inferer#137]
Upgrading to new versions of electron is critical for extracting new APIs from recent chromium versions. @sam016 investigated this (see https://github.com/amilajack/ast-metadata-inferer/issues/136#issuecomment-895244575) and ran into possible config issues related to electron 12. Needs further investigation.

**Comment by amilajack** [comment]
Awesome. Would you be interested in creating a PR with the fix?

**Comment by sam016** [comment]
Yes sure. thanks for the chance.
