### ISSUE TITLE
Redo the inferer to parse `@mdn/browser-compat-data` on import to allow users have control over which version of `@mdn/browser-compat-data` to use

### ISSUE THREAD

**Issue by yurijmikhalevich** [amilajack/ast-metadata-inferer#146]
Hi @amilajack 👋 

What do you think about redoing this module to infer `@mdn/browser-compat-data` on first load (or on install) and making `@mdn/browser-compat-data` a peerDependency? That way, users can update `@mdn/browser-compat-data` themselves.

Or alternatively, it is possible to set up CI to automatically update and release `ast-metadata-inferer` on new `@mdn-browser-compat-data` release.

What do you think?

**Comment by amilajack** [comment]
I'm going with the ci option for now

**Comment by yurijmikhalevich** [comment]
Hi @amilajack. Do you know whether this was resolved?
